---
title: "Tips + resources"
---

## Tips and tricks for visualisation

1. Consistency is the most important thing for a statistician.
   - jumping between different citation styles is bad
   - having some captions centered above the figure produced by R and others flushed right below using Markdown is annoying
2. Save space for better readability.
   - plots that convey little information don't have to be large, several (related) plots can be put next to each other on the same line, etc.
   - even in an `html` file, unnecessary scrolling back and forth when reading a report is annoying
   - a plot frame with one or two boxplots is a waste of space (e.g. histograms would be better)
   - barplots can often be replaced by tables to both save space and improve readability
   - in general, if a plot only shows like 3 numbers and is not important for any argument made, it should not be a plot
3. Story-telling matters.
   - it is important to grasp attention with an introduction (and describe at the same time what to expect from a report)
   - re-iterate the most important ideas/results in several places
   - comment on plots even if they are self-explanatory
4. More on plots.
   - text in figures (labels, etc.) should be of similar size as the main text
   - labels have to be readable, e.g. no overlaying etc.
   - captions are necessary and should make the plot self-contained (without looking at the paragraphs around it)
5. Less is sometimes more.
   - showing a scatterplot only to colors to it based on a group of two on the next plot, then adding one regression line, and then two regression lines on the fourth plot... just dilutes the important parts
   - Barplots colored by an additional variable should probably be replaced by a table (potentially colored by the cell
  values -- coloring for better readability only).
6. List of references should be itemized or enumerated (in order to be readable).
7. Avoid using local paths.
   - reproducibility of the report itself!
8. Transforming variables.
   - if your plots look bad because of a clear skewing in one of the variables, transform the varible (typically plot it on a log-scale)
   - if plotting on a log-scale, consider `log10` or `log2` to have better interpretability
  


## Some Links to Open Data

- [fivethirtyeight](https://data.fivethirtyeight.com/): article data of Nate Silver's data journalism platform freely available (see also R package - [fivethirtyeight](https://cran.r-project.org/web/packages/fivethirtyeight/index.html))

- [data-is-plural](https://www.data-is-plural.com/): weekly newsletter of datasets by Jeremy Singer-Vine

- [re3data](https://www.re3data.org/): Registry of research data repositories

- [openml datasets](https://www.openml.org/): many uniformly formatted datasets for training machine learning models -- however, not always good descriptions available

- [Worldbank Datacatalog](https://datacatalog.worldbank.org/): the World Bank data catalogue

- [UK Data Service](https://beta.ukdataservice.ac.uk/datacatalogue/studies#!?Search=&Rows=10&Sort=0&DateFrom=1753&DateTo=2018&AccessFacet=Open&Page=1): UK’s largest collection of social, economic and population data resources (filter for open data) or also [data.gov.uk](https://www.data.gov.uk/)

- [ICPSR](https://www.icpsr.umich.edu): unit within the Institute for Social Research at the University of Michigan, social and behavioral research. In particular including [replication datasets](https://www.openicpsr.org/openicpsr/) for published studies.

- [govdata](https://www.govdata.de/): Open Government - German administrative data freely accessible

- [gapminder](https://www.gapminder.org/): "an independent educational non-proﬁt ﬁghting global misconceptions"; collection and vizualisation of datasets concerning gobal developement

- [nature.com](https://www.nature.com/sdata/): peer-reviewed, open-access journal for descriptions of datasets (broad range of natural science disciplines)

- [NIH (National Institute of Health) Data Sharing Repositories](https://www.nlm.nih.gov/NIHbmic/domain_specific_repositories.html): overview on different thematically sorted medical databases

- [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets.php) or the new [beta version](https://archive-beta.ics.uci.edu/): containing various datasets -- however, sometimes with a little few description

- [data.bris Research Data Repository](https://data.bris.ac.uk/data/): Data repository of the University of Bristol

_... no systematic selection. Much more out there_



